general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hypr-lid-manager resume
    inhibit_sleep = 3                           # wait for the session-locker before suspending.
}

listener {
    timeout = 600                                 # 10min
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

listener {
    timeout = 660                                                     # 11min
    on-timeout = hypr-lid-manager idle-dpms
    on-resume = hypr-lid-manager resume
}

listener {
    timeout = 900                                 # 15min
    on-timeout = hypr-lid-manager idle-suspend
}
