directory: /mnt/f/Torrents/YtAudio/Plex/
library: ~/.config/beets/library.db

import:
  move: yes
  copy: no
  write: yes
  autotag: yes
  resume: ask
  incremental: no
  timid: no
  quiet: no
  quiet_fallback: skip
  group_albums: no
  from_scratch: no
  log: ~/.config/beets/import.log

paths:
  default: $albumartist/$album/$track - $title

replace:
  '[\\/]': _
  '^\.': _
  '[\x00-\x1f]': _
  '[<>:"\?\*\|]': _
  '\s+$': ''
  '^\s+': ''

art_filename: cover
threaded: yes
per_disc_numbering: no
plugins: 
    - musicbrainz
    
musicbrainz:
  host: musicbrainz.org
  https: yes
  ratelimit: 1
  ratelimit_interval: 1.0
  extra_tags: []
  genres: yes
  genres_tag: genre
  external_ids:
    discogs: no
    bandcamp: no
    spotify: no
    deezer: no
    beatport: no
    tidal: no
  data_source_mismatch_penalty: 0.5
  search_limit: 5
